name: kmeRNA_pipeline_env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.9
  - viennarna
  - numpy
  - scipy
  - scikit-learn
  - scikit-bio
  - pandas
  - matplotlib
  - tensorflow
  - joblib
  - matplotlib
  - biopython
  - keras=3
  - shap
  - pybedtools
  - pyfaidx
